version: '3'

services:
  mongo_db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - custom
    restart: always
    volumes:
      - db_data:/data/db
    env_file:
      - .env.mongo

  bot:
    build:
      context: "./bot"
      dockerfile: Dockerfile
    restart: always
    networks:
      - custom

networks:
  custom:
    driver: bridge


volumes:
  db_data: